// File: src/main/java/com/pahanaedu/billingsystem/model/Item.java
package com.pahanaedu.billingsystem.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a billing item (e.g., electricity, water, etc.) in MongoDB.
 * This will be used by the admin to set unit prices.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "items")
public class Item {

    /**
     * The unique ID for the item, auto-generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * The name of the billing item (e.g., "Electricity Unit").
     */
    private String name;

    /**
     * The price per unit of the item.
     */
    private double unitPrice;

    /**
     * A brief description of the item.
     */
    private String description;
}
